name: deploy-pages
triggers:
  push:
jobs:
  deploy:
    image: alios-8u
    steps:
      - uses: checkout

      - id: build-website
        run: |
          mkdir -p build
          cp index.html presentation-doc.html ppt-presentation.html build/
          cp -r res build/
          ls -la build/

      - uses: deploy-pages
        inputs:
          deploy-dir: build/
          production-branch: main
